services:
  postgres:
    image: postgres:17
    container_name: taskforge-postgres
    environment:
      POSTGRES_USER: taskforge
      POSTGRES_PASSWORD: taskforge
      POSTGRES_DB: taskforge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management
    container_name: taskforge-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: taskforge
      RABBITMQ_DEFAULT_PASS: taskforge
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build: .
    container_name: taskforge-api
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
      RABBITMQ_URL: ${RABBITMQ_URL_DOCKER}
    ports:
      - "8080:8080"

  worker:
    build: .
    container_name: taskforge-worker
    command: ["./worker"]
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
      RABBITMQ_URL: ${RABBITMQ_URL_DOCKER}

volumes:
  postgres_data:
